# Generated by Django 4.1.7 on 2023-03-30 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_rename_isssued_quantity_product_issued_quantity_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
