# Generated by Django 4.1.7 on 2023-03-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_alter_sale_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
