# Generated by Django 4.1.7 on 2023-03-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_alter_sale_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
