# Generated by Django 4.1.7 on 2023-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_alter_sale_amount_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recieved_quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
